import type { Metadata } from 'next';
import { PageHero } from '@/components/PageHero';
import { siteConfig } from '@/data/site';

export const metadata: Metadata = { title: 'Privacy policy', robots: { index: false, follow: true }, alternates: { canonical: '/privacy' } };

export default function PrivacyPage() {
  return <main><PageHero eyebrow="Informativa / Privacy" title="Privacy policy." intro="Bozza operativa da completare con i dati del titolare prima della pubblicazione." meta="Ultimo aggiornamento: 10 settembre 2026" /><article className="legal-page shell"><div className="notice-box"><span>Da completare</span><p>Questa informativa contiene campi segnaposto. Deve essere verificata in base agli strumenti effettivamente attivati sul sito.</p></div><h2>1. Titolare del trattamento</h2><p>Christian D’Ambrosio — P.IVA {siteConfig.vat} — Email {siteConfig.email}.</p><h2>2. Dati raccolti</h2><p>Attraverso il modulo di contatto possono essere raccolti nome, attività, indirizzo email, telefono facoltativo, tipo di progetto, budget indicativo facoltativo e contenuto del messaggio.</p><h2>3. Finalità e base giuridica</h2><p>I dati vengono utilizzati esclusivamente per rispondere alla richiesta e valutare un eventuale rapporto professionale. La base giuridica è l’esecuzione di misure precontrattuali richieste dall’interessato.</p><h2>4. Modalità e conservazione</h2><p>I dati vengono trattati con strumenti digitali e conservati per il tempo necessario a gestire la richiesta, salvo obblighi di legge o successivo rapporto contrattuale. Definire il periodo esatto prima della pubblicazione.</p><h2>5. Servizi esterni</h2><p>Il modulo è predisposto per Netlify Forms. Prima della pubblicazione vanno verificati hosting, localizzazione dei dati, eventuali responsabili del trattamento e relativi accordi.</p><h2>6. Diritti</h2><p>Puoi chiedere accesso, rettifica, cancellazione, limitazione, opposizione o portabilità scrivendo al recapito del titolare. Resta possibile proporre reclamo al Garante per la protezione dei dati personali.</p><h2>7. Modifiche</h2><p>L’informativa può essere aggiornata quando cambiano strumenti o modalità di trattamento.</p></article></main>;
}
